### ISSUE TITLE
Cannot send a plan message 

### ISSUE THREAD

**Issue by thuhc** [proximax-storage/java-xpx-chain-sdk#143]
1. Expected behavior and actual behavior.
Send a plan message between two accounts

2. Steps to reproduce the problem.
Call this function:
```
public static String sendPlainMessage(NetworkType networkType, String apiUrl, String senderPrivateKey, String recipientAddress, String message) throws Exception {
        final Account account = Account.createFromPrivateKey(senderPrivateKey, networkType);
        BlockchainApi blockchainApi = new BlockchainApi(new URL(apiUrl), networkType);
        final TransferTransaction transferTransaction = blockchainApi.transact().transfer()
                .deadline(Deadline.create(1, ChronoUnit.HOURS))
                .to(Address.createFromRawAddress(recipientAddress))
                .mosaics(new ArrayList<Mosaic>())
                .message(PlainMessage.create(message))
                .networkType(networkType)
                .build();
        final SignedTransaction signedTransaction = blockchainApi.sign(transferTransaction, account);
        final TransactionRepository transactionHttp = blockchainApi.createTransactionRepository();
        transactionHttp.announce(signedTransaction).toFuture().get();        
        System.out.println("Thread " +Thread.currentThread().getId() + ": " + signedTransaction.getHash());
        return signedTransaction.getHash();
    }
```

3. Specifications like the version of the project, operating system, or hardware.
Network Type: TEST_NET
Network URL:   http://bctestnet1.brimstone.xpxsirius.io:3000
java-xpx-chain-sdk: 0.6.1 version

Exception
```
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 2818572291 at line 1 column 480 path $.block.version
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:227)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:217)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        at com.google.gson.Gson.fromJson(Gson.java:852)
        at com.google.gson.Gson.fromJson(Gson.java:801)
        at com.google.gson.Gson.fromJson(Gson.java:773)
        at io.proximax.sdk.infrastructure.BlockchainHttp.lambda$getBlockByHeight$0(BlockchainHttp.java:64)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:66)
        at io.proximax.sdk.infrastructure.OkHttpHttpClient.lambda$createHttpResponseObservable$0(OkHttpHttpClient.java:107)
        at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableTimeoutTimed.subscribeActual(ObservableTimeoutTimed.java:47)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.Observable.blockingFirst(Observable.java:5119)
        at io.proximax.sdk.BlockchainApi.getNetworkGenerationHash(BlockchainApi.java:210)
        at io.proximax.sdk.BlockchainApi.sign(BlockchainApi.java:186)
        at io.proximax.utils.TransactionHelper.sendPlainMessage(TransactionHelper.java:46)
        at io.proximax.test.RunnerTxn.sendRandomMessage(RunnerTxn.java:85)
        at io.proximax.test.RunnerTxn.activeAccount(RunnerTxn.java:138)
        at io.proximax.test.RunnerTxn.run(RunnerTxn.java:133)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: Expected an int but was 2818572291 at line 1 column 480 path $.block.version
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1172)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:225)
        ... 32 more

```

**Comment by tonowie** [comment]
the issue is that java SDK tries to retrieve network generation hash as integer from block 1 property block.version and it has value 2818572291 which is outside of the range of signed integer.

Previously version was indicated as negative number when it used the most significant bit, now it is unsigned integer. I will need to change openapi spec to declare use of long and change implementation of DTOs to handle the value as long.
Need to review the impact as version is used in many places, not just block info

**Comment by tonowie** [comment]
hm, ok this was actually already done in 0.6.2 release which is currently available only as a snapshot release. Can you please try to use the snapshot release?
https://oss.sonatype.org/content/repositories/snapshots/io/proximax/java-xpx-chain-sdk/0.6.2-SNAPSHOT/

**Comment by tonowie** [comment]
the fix was made in pull request #142 for issue #141

**Comment by thuhc** [comment]
Thanks @tonowie , 

I just quick check your snapshot - My function worked normal

**Comment by tonowie** [comment]
requested public release https://github.com/proximax-storage/infrastructure-service-helpdesk/issues/2
